default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: family_be_development
  password: 123456
  host: localhost

test:
  <<: *default
  username: family_be_test
  password: 123456
  host: localhost

production:
  <<: *default
  database: family_be_production
  username: family_be
  password: 123456
